import React from 'react';

export default function IndexSection__structures32() {
    return (
        <React.Fragment>
            <>
                <section className="py-20 bg-yellow-50">  <div className="container mx-auto px-4">    <div className="flex justify-center mb-6" />    <h1 className="font-heading text-center text-4xl lg:text-5xl font-bold max-w-2xl lg:max-w-5xl mx-auto mb-4 tracking-widest">STUDIO PHOTOGRAPHY</h1>    <p className="text-gray-600 text-center max-w-xl mx-auto mb-12">Studio photography plays a key role in showcasing our products with clarity and consistency. Product shots ensure a polished, professional look that highlights details without distractions. These images are primarily used for our e-commerce site and social channels.</p>    <div className="flex flex-wrap -m-4 mb-12" />    <div className="flex flex-wrap -m-4">      <div className="w-full lg:w-1/3 p-4">        <div className="mb-10">          <img className="w-full object-cover" style={{height: 400}} src="https://static.shuffle.dev/uploads/files/ee/ee137d2a3df0a9e3dc5d8722b3ba155636636edc/00019.jpg" alt />      </div>        <h2 className="font-heading font-bold max-w-lg mb-4 tracking-widest text-2xl">ITEMS WITHOUT HIGH-QUALITY IMAGES</h2>        <p className="text-gray-600 text-xl mb-6 max-w-2xl">Some brands either lack an asset library or do not grant us access to their images. In these cases, any product without high-quality imagery must be photographed before being added to our website. This ensures a consistent, professional presentation that accurately reflects the quality and details of our products.</p>    </div>      <div className="w-full lg:w-1/3 p-4">        <div className="mb-10">          <img className="w-full object-cover" style={{height: 400}} src="https://static.shuffle.dev/uploads/files/ee/ee137d2a3df0a9e3dc5d8722b3ba155636636edc/lg-harvey-1.jpg" alt />      </div>        <h2 className="font-heading font-bold max-w-lg mb-4 tracking-widest text-2xl">HARVEY MERCH</h2>        <p className="text-gray-600 text-xl mb-6 max-w-2xl">Key items, include Harvey’s merch—including stuffed Harvey dogs, sweatshirts, totes, mugs and more. Other examples include Michigan Made products like Sozo Coffee and Cherry Republic.</p>    </div>      <div className="w-full lg:w-1/3 p-4">        <div className="mb-10">          <img className="w-full object-cover" style={{height: 400}} src="https://static.shuffle.dev/uploads/files/ee/ee137d2a3df0a9e3dc5d8722b3ba155636636edc/106904-A35-WS25-e-V2.jpg" alt />      </div>        <h2 className="font-heading font-bold max-w-lg mb-4 tracking-widest text-2xl">BRAND ASSETS</h2>        <p className="text-gray-600 text-xl mb-6 max-w-2xl">Product shots are available through Brand Photography Assets and should be utilized for e-commerce site. It is important these all use a white backdrop and size consistency. Image provided from Carhartt assets.</p>    </div>  </div></div></section>


            </>
        </React.Fragment>
    );
}

