import React from 'react';

export default function IndexSection__structures28() {
    return (
        <React.Fragment>
            <>
                <section className="py-20">  <div className="container mx-auto px-4">                <div className="flex flex-wrap items-center -m-4 mb-16">      <div className="w-full lg:w-5/12 p-4 order-2 lg:order-1">        <p className="font-bold mb-3 text-orange-500 font-heading text-2xl tracking-widest">BUILT WITH CARE, CAPTURED WITH PURPOSE</p>        <p className="text-gray-600 mb-4">We document the entire journey with a blend of shots capturing our facilities, processes, and the people behind our work. These images offer a comprehensive look at the care and effort that go into every step of what we do.</p>    </div>      <div className="w-full lg:w-7/12 p-4 order-1 lg:order-2">        <img className="w-full object-cover max-h-96" src="https://static.shuffle.dev/uploads/files/ee/ee137d2a3df0a9e3dc5d8722b3ba155636636edc/Mill-Exterior-1-1-2-copy.jpg" alt />    </div>  </div>    <div className="flex flex-wrap items-center -m-4 mb-16">      <div className="w-full lg:w-7/12 p-4">        <img className="w-full object-cover max-h-96" src="https://static.shuffle.dev/uploads/files/ee/ee137d2a3df0a9e3dc5d8722b3ba155636636edc/Emberglow-0016-1-copy.jpg" alt />    </div>      <div className="w-full lg:w-5/12 p-4">        <p className="font-bold mb-3 text-orange-500 font-heading text-2xl tracking-widest">REAL HARDWORKING PEOPLE</p>        <p className="text-gray-600 mb-4">We combine aerial shots with close-ups to contrast large-scale operations with the human effort behind them.</p>    </div>  </div>    <div className="flex flex-wrap items-center -m-4 mb-16">      <div className="w-full lg:w-5/12 p-4 order-2 lg:order-1">        <p className="font-bold mb-3 text-orange-500 font-heading text-2xl tracking-widest">EVERY SEASON, EVERY DETAIL</p>        <p className="text-gray-600 mb-4">We capture close-up shots in the fields to highlight our products, the process of crop rotation, and change of seasons.</p>    </div>      <div className="w-full lg:w-7/12 p-4 order-1 lg:order-2">        <img className="w-full object-cover max-h-96" src="https://images.unsplash.com/photo-1567547921486-f280c2f53b5d?crop=entropy&cs=srgb&fm=jpg&ixid=M3wzMzIzMzB8MHwxfHNlYXJjaHwyfHxjb3JuJTIwZmllbGR8ZW58MHx8fHwxNzQyNDAwMjk1fDA&ixlib=rb-4.0.3&q=85&w=1920" alt />    </div>  </div>    <div className="flex flex-wrap items-center -m-4">      <div className="w-full lg:w-7/12 p-4">        <img className="w-full object-cover max-h-96" src="https://static.shuffle.dev/uploads/files/ee/ee137d2a3df0a9e3dc5d8722b3ba155636636edc/IMG-3540.JPG" alt />    </div>      <div className="w-full lg:w-5/12 p-4">        <p className="font-bold mb-3 text-orange-500 font-heading text-2xl tracking-widest">AUTHENTICITY IN EVERY FRAME</p>        <p className="text-gray-600 mb-4">We capture the genuine connections we share with both employees and customers. Every shot is authentic—no fakes, no staging—just real moments with real people.</p>    </div>  </div></div></section>


            </>
        </React.Fragment>
    );
}

