#!/usr/bin/env node
// Generates packages/tokens/dist/* from DESIGN.md's YAML frontmatter — the
// single machine-readable token source. Zero dependencies on purpose: the
// frontmatter is a controlled subset of YAML (maps, one list level, quoted
// scalars, comments) and taking on a YAML lib would pollute the pinned
// lockfile. dist/ is COMMITTED; consumers vendor from it. Never hand-edit
// dist — tokens.test.mjs fails on any divergence from a regeneration.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const DESIGN = join(here, "..", "..", "DESIGN.md");
const DIST = join(here, "dist");

// ---------- frontmatter parser (controlled subset) ----------
function parseFrontmatter(src) {
  const m = src.match(/^---\n([\s\S]*?)\n---/);
  if (!m) throw new Error("DESIGN.md has no frontmatter");
  const root = {};
  // stack of [indent, container, keyInParent, parentContainer]
  const stack = [[-1, root, null, null]];
  for (const raw of m[1].split("\n")) {
    if (!raw.trim() || raw.trim().startsWith("#")) continue;
    const indent = raw.length - raw.trimStart().length;
    const line = raw.trim();
    while (stack.length > 1 && indent <= stack[stack.length - 1][0]) stack.pop();
    const top = stack[stack.length - 1];
    if (line.startsWith("- ")) {
      if (!Array.isArray(top[1])) {
        if (Object.keys(top[1]).length !== 0 || !top[3])
          throw new Error(`list item under a non-empty map: ${line}`);
        const arr = [];
        top[3][top[2]] = arr;
        top[1] = arr;
      }
      top[1].push(cleanValue(line.slice(2)));
      continue;
    }
    const parent = top[1];
    const ci = line.indexOf(":");
    const key = line.slice(0, ci).trim();
    const rest = line.slice(ci + 1).trim();
    if (rest === "") {
      const child = {};
      parent[key] = child;
      stack.push([indent, child, key, parent]);
    } else {
      parent[key] = cleanValue(rest);
    }
  }
  return root;
}

function cleanValue(v) {
  v = v.trim();
  if (v.startsWith('"')) {
    const end = v.indexOf('"', 1);
    return v.slice(1, end);
  }
  // unquoted: strip trailing comment
  const hash = v.indexOf(" #");
  if (hash !== -1) v = v.slice(0, hash).trim();
  return v;
}

// ---------- assembly ----------
const doc = parseFrontmatter(readFileSync(DESIGN, "utf8"));
const { colors, dataviz, rounded, spacing, typography, effects } = doc;

// Font stacks are assembled here (the frontmatter names faces, not stacks).
// TT Commons Pro leads the body stack as a documented no-op until the
// Typekit domain list is extended (tokens-25).
const FONT_DISPLAY =
  '"Chakra Petch", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif';
const FONT_BODY =
  '"TT Commons Pro", "Open Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif';

const flat = { ...colors };
const datavizVars = {};
(dataviz.categorical || []).forEach((v, i) => (datavizVars[`cat-${i + 1}`] = v));
(dataviz.sequential || []).forEach((v, i) => (datavizVars[`seq-${i + 1}`] = v));
(dataviz.diverging || []).forEach((v, i) => (datavizVars[`div-${i + 1}`] = v));

// tokens.css
let css = `/* Generated by packages/tokens/build.mjs from DESIGN.md — do not edit. */\n:root {\n`;
for (const [k, v] of Object.entries(flat)) css += `  --hb-${k}: ${v};\n`;
for (const [k, v] of Object.entries(datavizVars)) css += `  --hb-${k}: ${v};\n`;
for (const [k, v] of Object.entries(rounded))
  css += `  --hb-radius${k === "DEFAULT" ? "" : `-${k}`}: ${v};\n`;
for (const [k, v] of Object.entries(spacing)) {
  css +=
    k === "touch-target-min"
      ? `  --hb-touch-target-min: ${v};\n`
      : `  --hb-space-${k}: ${v};\n`;
}
for (const [k, v] of Object.entries(effects || {})) css += `  --hb-${k}: ${v};\n`;
css += `  --hb-font-display: ${FONT_DISPLAY};\n`;
css += `  --hb-font-body: ${FONT_BODY};\n`;
css += `}\n`;

// tokens.json
const json = {
  colors,
  dataviz,
  rounded,
  spacing,
  typography,
  effects: effects || {},
  fonts: { display: FONT_DISPLAY, body: FONT_BODY },
};

// tokens.mjs / tokens.ts — literal-hex constants for paint contexts where
// var() cannot resolve (SVG attributes, canvas, map paint, color math).
const constName = (k) => k.toUpperCase().replace(/-/g, "_");
let consts = `// Generated by packages/tokens/build.mjs from DESIGN.md — do not edit.\n`;
consts += `export const HB = ${JSON.stringify(flat, null, 2)};\n`;
for (const [k, v] of Object.entries(flat))
  consts += `export const ${constName(k)} = ${JSON.stringify(v)};\n`;
consts += `export const CATEGORICAL = ${JSON.stringify(dataviz.categorical)};\n`;
consts += `export const SEQUENTIAL = ${JSON.stringify(dataviz.sequential)};\n`;
consts += `export const DIVERGING = ${JSON.stringify(dataviz.diverging)};\n`;
consts += `export const FONT_DISPLAY = ${JSON.stringify(FONT_DISPLAY)};\n`;
consts += `export const FONT_BODY = ${JSON.stringify(FONT_BODY)};\n`;

// tailwind-preset.cjs — hb-* color utilities as var() with baked hex
// fallbacks, so kit components render true even where tokens.css is not
// loaded. Extend-only: safe to add to any Tailwind 3 config's presets.
const presetColors = {};
for (const [k, v] of Object.entries(flat))
  presetColors[`hb-${k}`] = `var(--hb-${k}, ${v})`;
presetColors["hb-ink"] = `var(--hb-black, ${flat.black})`; // alias: ink
for (const [k, v] of Object.entries(datavizVars))
  presetColors[`hb-${k}`] = `var(--hb-${k}, ${v})`;

const preset = `// Generated by packages/tokens/build.mjs from DESIGN.md — do not edit.
// Extend-only Tailwind 3 preset: hb-* semantic colors (var + baked hex
// fallback), the brand keyframes, small-caps tracking, and duration-250.
// No alpha modifiers on hb-* colors (they are var() strings) — the one
// sanctioned alpha use, the bg-black/80 scrim, stays a literal utility.
module.exports = {
  theme: {
    extend: {
      colors: ${JSON.stringify(presetColors, null, 8).replace(/\n}/, "\n      }")},
      letterSpacing: {
        smallcaps: "0.08em",
      },
      transitionDuration: {
        250: "250ms",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "collapsible-down": { from: { height: "0" }, to: { height: "var(--radix-collapsible-content-height)" } },
        "collapsible-up": { from: { height: "var(--radix-collapsible-content-height)" }, to: { height: "0" } },
        "monogram-spin": { to: { transform: "rotate(360deg)" } },
        "monogram-breathe": {
          "0%, 100%": { transform: "scale(0.96)", opacity: "0.72" },
          "50%": { transform: "scale(1)", opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "collapsible-down": "collapsible-down 0.2s ease-out",
        "collapsible-up": "collapsible-up 0.2s ease-out",
        "monogram-spin": "monogram-spin 1.05s cubic-bezier(0.65,0,0.35,1) infinite",
        "monogram-breathe": "monogram-breathe 1.8s ease-in-out infinite",
      },
    },
  },
};
`;

mkdirSync(DIST, { recursive: true });
writeFileSync(join(DIST, "tokens.css"), css);
writeFileSync(join(DIST, "tokens.json"), JSON.stringify(json, null, 2) + "\n");
writeFileSync(join(DIST, "tokens.mjs"), consts);
writeFileSync(
  join(DIST, "tokens.ts"),
  consts.replace("export const HB =", "export const HB: Record<string, string> =")
);
writeFileSync(join(DIST, "tailwind-preset.cjs"), preset);
console.log(
  `tokens: ${Object.keys(flat).length} colors, ${Object.keys(datavizVars).length} dataviz vars → dist/`
);
